import { ApiInterface, ApiResponse, Co2Summary } from './Co2Summary'

class ApiStub implements ApiInterface {
  co2Information(): ApiResponse {
    return api;
  }
}

describe('fetch co2', () => {
  test('should return co2 information from the api', () => {
    const co2 = new Co2Summary(new ApiStub())
    const burnedCo2 = co2.fetch()

    expect(burnedCo2).toEqual(1246.9)
  })
})

const api: ApiResponse = {
    "582073": {
      "id": "582073",
      "timezone": "-3",
      "plantName": "Aron Solar",
      "plantData": {
        "valleyPeriodPrice": "1.0",
        "formulaTree": "0.055",
        "flatPeriodPrice": "1.1",
        "co2": "1246.9",
        "lng": "-42.34331212764",
        "designCompany": "0",
        "moneyUnit": "real",
        "peakPeriodPrice": "1.3",
        "formulaCoal": "0.4",
        "city": "Araruama",
        "nominalPower": "5700",
        "id": "582073",
        "timezone": "-3",
        "tree": "171",
        "coal": "1246.9",
        "locationImg": "null",
        "fixedPowerPrice": "1.2",
        "moneyUnitText": "R$",
        "lat": "-22.88201249046",
        "plantImg": "582073_1images1618149089218.jpg",
        "plantName": "Aron Solar",
        "creatDate": "2021-04-10",
        "eTotal": "3117.3",
        "formulaCo2": "0.4",
        "plantType": "0",
        "country": "Brazil",
        "accountName": "aronpc",
        "formulaMoney": "0.0",
        "isShare": "false"
      },
      "devices": {
        "YIDBA470E3": {
          "totalData": {
            "mUnitText": "R$",
            "eToday": "30.1",
            "eTotal": "3117.3",
            "mTotal": "3740.8",
            "mToday": "36.1"
          },
          "historyLast": {
            "serialNum": "YIDBA470E3",
            "address": 0,
            "calendar": "2021-09-04T19:33:26.000Z",
            "withTime": false,
            "status": 1,
            "isAgain": false,
            "lost": true,
            "ppv": 825.8,
            "ppv1": 564.3,
            "ppv2": 261.5,
            "ppv3": 0,
            "pac": 810.8,
            "pacToUserTotal": 0,
            "pacToGridTotal": 0,
            "pacToLocalLoad": 0,
            "timeTotal": 1169056.6,
            "epsPac": 0,
            "vpv1": 277.4,
            "ipv1": 1.9,
            "vpv2": 251.2,
            "ipv2": 0.9,
            "vpv3": 0,
            "ipv3": 0,
            "fac": 60.01,
            "vac1": 222.3,
            "iac1": 3.5,
            "pac1": 791.8,
            "vac2": 0,
            "iac2": 0,
            "pac2": 0,
            "vac3": 0,
            "iac3": 0,
            "pac3": 0,
            "vacRs": 222.3,
            "vacSt": 0,
            "vacTr": 0,
            "eacToday": 30.1,
            "eacTotal": 3117.3,
            "epv1Today": 14.9,
            "epv2Today": 14.8,
            "epv3Today": 0,
            "temp1": 39.3,
            "temp2": 0,
            "temp3": 0,
            "temp4": 0,
            "temp5": 44.1,
            "pBusVoltage": 360.1,
            "nBusVoltage": 0,
            "opFullwatt": 0,
            "invDelayTime": 0,
            "pf": 1,
            "epsPf": -1,
            "dcVoltage": 0,
            "epsFac": 0,
            "epsVac1": 0,
            "epsIac1": 0,
            "epsPac1": 0,
            "epsVac2": 0,
            "epsIac2": 0,
            "epsPac2": 0,
            "epsVac3": 0,
            "epsIac3": 0,
            "epsPac3": 0,
            "dciR": 10,
            "dciS": 0,
            "dciT": 0,
            "sysFaultWord": 0,
            "sysFaultWord1": 0,
            "sysFaultWord2": 0,
            "sysFaultWord3": 0,
            "sysFaultWord4": 0,
            "sysFaultWord5": 0,
            "sysFaultWord6": 0,
            "sysFaultWord7": 0,
            "faultType": 0,
            "warnCode": 0,
            "realOPPercent": 13,
            "deratingMode": 0,
            "bdcStatus": 0,
            "dryContactStatus": 0,
            "loadPercent": 0,
            "uwSysWorkMode": 0,
            "gfci": 72,
            "iso": 0,
            "etoUserToday": 0,
            "etoUserTotal": 0,
            "etoGridToday": 0,
            "etoGridTotal": 0,
            "elocalLoadToday": 0,
            "elocalLoadTotal": 0,
            "epv1Total": 1555.9,
            "epv2Total": 1522.9,
            "epv3Total": 0,
            "epvTotal": 3078.8,
            "echargeToday": 0,
            "echargeTotal": 0,
            "edischargeToday": 0,
            "edischargeTotal": 0,
            "eacChargeToday": 0,
            "eacChargeTotal": 0,
            "bdc1Status": 0,
            "bdc1Mode": 0,
            "bdc1FaultType": 0,
            "bdc1WarnCode": 0,
            "bdc1Vbat": 0,
            "bdc1Ibat": 0,
            "bdc1Soc": 0,
            "bdc1Vbus1": 0,
            "bdc1Vbus2": 0,
            "bdc1Ibb": 0,
            "bdc1Illc": 0,
            "bdc1Temp1": 0,
            "bdc1Temp2": 0,
            "bdc1DischargePower": 0,
            "bdc1ChargePower": 0,
            "bdc1DischargeTotal": 0,
            "bdc1ChargeTotal": 0,
            "bdc2Status": 0,
            "bdc2Mode": 0,
            "bdc2FaultType": 0,
            "bdc2WarnCode": 0,
            "bdc2Vbat": 0,
            "bdc2Ibat": 0,
            "bdc2Soc": 0,
            "bdc2Vbus1": 0,
            "bdc2Vbus2": 0,
            "bdc2Ibb": 0,
            "bdc2Illc": 0,
            "bdc2Temp1": 0,
            "bdc2Temp2": 0,
            "bdc2DischargePower": 0,
            "bdc2ChargePower": 0,
            "bdc2DischargeTotal": 0,
            "bdc2ChargeTotal": 0,
            "bmsStatus": 0,
            "bmsFaultType": 0,
            "bmsWarnCode": 0,
            "bmsVbat": 0,
            "bmsIbat": 0,
            "bmsSoc": 0,
            "bmsTemp1Bat": 0,
            "bmsMaxCurr": 0,
            "bmsVdelta": 0,
            "bmsIcycle": 0,
            "bmsSoh": 0,
            "bmsCvVolt": 0,
            "bmsInfo": 0,
            "bmsPackInfo": 0,
            "bmsUsingCap": 0,
            "bmsFwVersion": "0",
            "bmsMcuVersion": "0",
            "bmsCommunicationType": 0,
            "iacr": 0,
            "vacr": 0,
            "pacr": 0,
            "vacrs": 0,
            "operatingMode": 0,
            "ipv4": 0,
            "vpv4": 0,
            "ppv4": 0,
            "bdcFaultSubCode": 0,
            "bdcWarnSubCode": 0,
            "bdcBusRef": 0,
            "bdcVbus2Neg": 0,
            "bdcDerateReason": 0,
            "bmsError2": 0,
            "bmsError3": 0,
            "bmsWarn2": 0,
            "debug1": "165，0，0，0，381，0，0，0",
            "debug2": "0，0，0，0，0，0，0，0",
            "psystem": 0,
            "pself": 0,
            "esystemToday": 0,
            "esystemTotal": 0,
            "eselfToday": 0,
            "eselfTotal": 0,
            "bmsError4": 0,
            "bmsIosStatus": 0,
            "pex1": -0.1,
            "pex2": -0.1,
            "eex1Today": -0.1,
            "eex2Today": -0.1,
            "eex1Total": -0.1,
            "eex2Total": -0.1,
            "batteryNo": -1,
            "batterySN": "null"
          },
          "deviceData": {
            "pac": "810.8",
            "sn": "YIDBA470E3",
            "plantName": "Aron Solar",
            "location": "",
            "alias": "Casa",
            "status": "1",
            "eToday": "30.1",
            "lastUpdateTime": "2021-09-04 16:33:26",
            "datalogSn": "ZOD3A463Y5",
            "datalogTypeTest": "ShineWiFi-X",
            "deviceModel": "MIN 6000TL-X",
            "bdcStatus": "0",
            "deviceTypeName": "tlx",
            "eTotal": "3117.3",
            "eMonth": "120",
            "nominalPower": "6000",
            "accountName": "aronpc",
            "timezone": "-3",
            "timeServer": "2021-09-05 03:33:26",
            "plantId": "582073",
            "deviceType": "0"
          }
        }
      }
    }
  }
