version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"

  rabbitmq-api:
    image: aronpc/cati-php:8.0-fpm
    working_dir: /app
    depends_on:
      - rpc-server
    links:
      - rabbitmq
    volumes:
      - ./api:/app

  rpc-server:
    image: aronpc/cati-php:8.0-fpm
    working_dir: /app
    command: "composer server"
    links:
      - rabbitmq
    volumes:
      - ./api:/app