#.github/workflows/pr.yml
name: CI
on:
    - push

jobs:
    phpinsights:
        runs-on: ubuntu-latest
        name: PHP Insights checks
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
            - run: cd roman-numerals && composer install --prefer-dist --no-progress --no-suggest
            - run: cd roman-numerals && ./vendor/bin/phpinsights -n --ansi --format=github-action